grails-app/domain/org/rankster/User.groovy
package org.rankster

class User {

	transient springSecurityService

	String avatar
	String username
	String password
	String email
	String realName
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

	static hasMany = [groups: Group, memberships: Membership, ranks: Rank, participations: Participation]

    static mappedBy = [groups:'owner', ranks:'publisher']

	static transients = ['springSecurityService']

	static constraints = {
		username     blank: false, unique: true
		password     blank: false
		ranks        nullable: true
		groups       nullable: true
        avatar       nullable:true
	}

	static mapping = {
		table '_user'
		password column: '`password`'
	}

	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this).collect { it.role }
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}
    
    String toString(){
        return username
    }    


}

grails-app/controllers/org/rankster/UserController.groovy
package org.rankster


import org.springframework.security.access.annotation.Secured
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
@Secured(['IS_AUTHENTICATED_ANONYMOUSLY'])
class UserController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
    def springSecurityService

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond User.list(params), model:[userInstanceCount: User.count()]
    }

    def show(User userInstance) {
        respond userInstance
    }

    def create() {
        respond new User(params)
    }

    def register() {
        respond new User(params)
    }

    def myProfile(){
        def currentUser = springSecurityService.getCurrentUser()
        if(currentUser == null){
            redirect uri: "/"
        }else{
            def userInstance =  User.findById(currentUser.id) 
            respond userInstance 
        }
    }

    @Transactional
    def registerNewUser(User userInstance) {
        saveUser(userInstance)
    }

    @Transactional
    def save(User userInstance) {
        saveUser(userInstance)
        render view: view, model: [postUrl: postUrl,
                                   rememberMeParameter: config.rememberMe.parameter]
    }

    def edit(User userInstance) {
        respond userInstance
    }

    @Transactional
    def update(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }

        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:'edit'
            return
        }

        userInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect userInstance
            }
            '*'{ respond userInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(User userInstance) {

        if (userInstance == null) {
            notFound()
            return
        }

        userInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'User.label', default: 'User'), userInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

    private void saveUser(User userInstance) {
        if (userInstance == null) {
            notFound()
            return
        }
        if (userInstance.hasErrors()) {
            respond userInstance.errors, view:backTo
            return
        }
        userInstance.save flush:true
        redirect uri: '/'
    }

	@Transactional
	def uploadAvatar() {
		// captura o usuario atual
        def currentUser = springSecurityService.getCurrentUser()
        def userInstance =  User.findById(currentUser.id) 
		// cria o diretorio dos avatares
		String avatarDir = getAvatarDir(userInstance.id)

		// pega a image e salva 
		def f = request.getFile('avatarImage')
		if (f.empty) {
			flash.message = 'file cannot be empty'
			return
		}   
		String file_name = f.getOriginalFilename()
		String file_path = avatarDir+"/"+file_name
		userInstance.avatar = "user/"+userInstance.id+"/"+file_name 
        userInstance.save()
		// cria o arquivo
		f.transferTo(new File(file_path))
        redirect uri: "/user/myProfile"
	}

	def getAvatarDir(Long id){
		def webrootDir = servletContext.getRealPath("/") // app directory path
		String path = webrootDir+"images/user/"+id
		def directory = new File(path)	
		if(!directory.exists()){
			directory.mkdirs()
		}
		return path
	}
}

grails-app/views/user/_form.gsp
<%@ page import="org.rankster.User" %>



<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'username', 'error')} required">
	<label for="username">
		<g:message code="user.username.label" default="Username" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="username" required="" value="${userInstance?.username}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'password', 'error')} required">
	<label for="password">
		<g:message code="user.password.label" default="Password" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="password" required="" value="${userInstance?.password}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'ranks', 'error')} ">
	<label for="ranks">
		<g:message code="user.ranks.label" default="Ranks" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${userInstance?.ranks?}" var="r">
    <li><g:link controller="rank" action="show" id="${r.id}">${r?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="rank" action="create" params="['user.id': userInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'rank.label', default: 'Rank')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'groups', 'error')} ">
	<label for="groups">
		<g:message code="user.groups.label" default="Groups" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${userInstance?.groups?}" var="g">
    <li><g:link controller="group" action="show" id="${g.id}">${g?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="group" action="create" params="['user.id': userInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'group.label', default: 'Group')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'accountExpired', 'error')} ">
	<label for="accountExpired">
		<g:message code="user.accountExpired.label" default="Account Expired" />
		
	</label>
	<g:checkBox name="accountExpired" value="${userInstance?.accountExpired}" />

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'accountLocked', 'error')} ">
	<label for="accountLocked">
		<g:message code="user.accountLocked.label" default="Account Locked" />
		
	</label>
	<g:checkBox name="accountLocked" value="${userInstance?.accountLocked}" />

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'email', 'error')} required">
	<label for="email">
		<g:message code="user.email.label" default="Email" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="email" required="" value="${userInstance?.email}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'enabled', 'error')} ">
	<label for="enabled">
		<g:message code="user.enabled.label" default="Enabled" />
		
	</label>
	<g:checkBox name="enabled" value="${userInstance?.enabled}" />

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'memberships', 'error')} ">
	<label for="memberships">
		<g:message code="user.memberships.label" default="Memberships" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${userInstance?.memberships?}" var="m">
    <li><g:link controller="membership" action="show" id="${m.id}">${m?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="membership" action="create" params="['user.id': userInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'membership.label', default: 'Membership')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'participations', 'error')} ">
	<label for="participations">
		<g:message code="user.participations.label" default="Participations" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${userInstance?.participations?}" var="p">
    <li><g:link controller="participation" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="participation" action="create" params="['user.id': userInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'participation.label', default: 'Participation')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'passwordExpired', 'error')} ">
	<label for="passwordExpired">
		<g:message code="user.passwordExpired.label" default="Password Expired" />
		
	</label>
	<g:checkBox name="passwordExpired" value="${userInstance?.passwordExpired}" />

</div>

<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'realName', 'error')} required">
	<label for="realName">
		<g:message code="user.realName.label" default="Real Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="realName" required="" value="${userInstance?.realName}"/>

</div>

grails-app/views/user/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-user" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${userInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${userInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:userInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/user/edit.gsp
<%@ page import="org.rankster.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-user" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-user" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${userInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${userInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:userInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${userInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/user/index.gsp
<%@ page import="org.rankster.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title>  Users   </title>
	</head>
	<body>
		<div id="list-user" class="content scaffold-list" role="main">
    
            <h1> Users </h1>
            <hr>
                    <div class="row">
				<g:each in="${userInstanceList}" status="i" var="userInstance">

                      <div class="col-sm-6 col-md-4">
                        <div class="thumbnail">
                            <g:if test="${userInstance?.avatar}">
                                <!-- avatar image displayed   -->
                                <g:img dir="images" file="${userInstance.avatar} " width="200" height="100"class="img-thumbnail"/>
                            </g:if>
                            <g:else>
                                <!-- default image displayed   -->
                                <g:img dir="images" file="user/default/avatar.png" width="200" height="100"class="img-thumbnail" style="margin-bottom:40px;"/>
                            </g:else>
                          <div class="caption text-center">
						    <g:link  action="show" id="${userInstance.id}" >
                                    ${fieldValue(bean: userInstance, 
                                    field: "username")}
                            </g:link>
                          </div>
                        </div>
                      </div>
				</g:each>
                    </div>
			<div class="pagination">
				<g:paginate total="${userInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/user/myProfile.gsp
<!DOCTYPE html>
<html>
<head>
		<meta name="layout" content="main">
		<title> My Profile </title>
</head>
<body>
	<div class='container'>

		<g:if test="${userInstance?.avatar}">
			<!-- avatar image displayed   -->
			<g:img dir="images" file="${userInstance.avatar} " width="200" height="100"class="img-thumbnail"/>
		</g:if>
		<g:else>
			<!-- default image displayed   -->
			<g:img dir="images" file="user/default/avatar.png" width="200" height="100"class="img-thumbnail"/>
		</g:else>

		<g:uploadForm action="uploadAvatar">
			<input type="file" name="avatarImage" />
			<input type="submit" value="Change" />
		</g:uploadForm>	
		<hr>

		<g:if test="${userInstance?.realName}">
			<span id="realName-label" class="property-label"><g:message code="user.realName.label" default="Real Name" />:</span>
			<span class="property-value" aria-labelledby="realName-label"><g:fieldValue bean="${userInstance}" field="realName"/></span>
		<hr>	
		</g:if>
		<g:if test="${userInstance?.username}">
			<span id="username-label" class="property-label"><g:message code="user.username.label" default="Username" />:</span>
			<span class="property-value" aria-labelledby="username-label"><g:fieldValue bean="${userInstance}" field="username"/></span>
		<hr>
		</g:if>
		<g:if test="${userInstance?.email}">
			<span id="email-label" class="property-label"><g:message code="user.email.label" default="Email" />:</span>
			<span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${userInstance}" field="email"/></span>
		<hr>
		</g:if>
		<g:if test="${userInstance?.groups}">
					<span id="groups-label" class="property-label"><g:message code="user.groups.label" default="Groups" /></span>
						<g:each in="${userInstance.groups}" var="g">
						<span class="property-value" aria-labelledby="groups-label"><g:link controller="group" action="show" id="${g.id}">${g?.encodeAsHTML()}</g:link></span>
						</g:each>
		<hr>
		</g:if>
				
		<g:if test="${userInstance?.memberships}">
			<span id="memberships-label" class="property-label"><g:message code="user.memberships.label" default="Memberships" /></span>
				<g:each in="${userInstance.memberships}" var="m">
				<span class="property-value" aria-labelledby="memberships-label"><g:link controller="membership" action="show" id="${m.id}">${m?.encodeAsHTML()}</g:link></span>
				</g:each>
		<hr>
		</g:if>
	</div>
</body>
</html>

grails-app/views/user/register.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main">
        <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <div id="create-user" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${userInstance}">
            <ul class="errors" role="alert">
                <g:eachError bean="${userInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form url="[resource:userInstance, action:'registerNewUser']" >
                <fieldset class="form">
                    <div class="fieldcontain ${hasErrors(bean: userInstance, field: 'realName', 'error')} required">
                        <label for="realName">
                            <g:message code="user.realName.label" default="Real Name" />
                            <span class="required-indicator">*</span>
                        </label>
                        <g:textField name="realName" required="" value="${userInstance?.realName}"/>
                    </div>
                    <div class="fieldcontain ${hasErrors(bean: userInstance, field: 'username', 'error')} required">
                        <label for="username">
                            <g:message code="user.username.label" default="Username" />
                            <span class="required-indicator">*</span>
                        </label>
                        <g:textField name="username" required="" value="${userInstance?.username}"/>
                    </div>
                    <div class="fieldcontain ${hasErrors(bean: userInstance, field: 'password', 'error')} required">
                        <label for="password">
                            <g:message code="user.password.label" default="Password" />
                            <span class="required-indicator">*</span>
                        </label>
                        <g:passwordField name="password" required="" value="${userInstance?.password}"/>
                    </div>
                    <div class="fieldcontain ${hasErrors(bean: userInstance, field: 'email', 'error')} required">
                        <label for="email">
                            <g:message code="user.email.label" default="Email" />
                            <span class="required-indicator">*</span>
                        </label>
                        <g:textField name="email" required="" value="${userInstance?.email}"/>
                    </div>

                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="register" class="save" value="${message(code: 'default.button.register.label', default: 'Register')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/user/show.gsp
<%@ page import="org.rankster.User" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'user.label', default: 'User')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
        <div class='container'>

            <g:if test="${userInstance?.avatar}">
                <!-- avatar image displayed   -->
                <g:img dir="images" file="${userInstance.avatar} " width="200" height="100"class="img-thumbnail"/>
            </g:if>
            <g:else>
                <!-- default image displayed   -->
                <g:img dir="images" file="user/default/avatar.png" width="200" height="100"class="img-thumbnail"/>
            </g:else>

            <hr>

            <g:if test="${userInstance?.realName}">
                <span id="realName-label" class="property-label"><g:message code="user.realName.label" default="Real Name" />:</span>
                <span class="property-value" aria-labelledby="realName-label"><g:fieldValue bean="${userInstance}" field="realName"/></span>
            <hr>
            </g:if>
            <g:if test="${userInstance?.username}">
                <span id="username-label" class="property-label"><g:message code="user.username.label" default="Username" />:</span>
                <span class="property-value" aria-labelledby="username-label"><g:fieldValue bean="${userInstance}" field="username"/></span>
            <hr>
            </g:if>
            <g:if test="${userInstance?.email}">
                <span id="email-label" class="property-label"><g:message code="user.email.label" default="Email" />:</span>
                <span class="property-value" aria-labelledby="email-label"><g:fieldValue bean="${userInstance}" field="email"/></span>
            <hr>
            </g:if>
            <g:if test="${userInstance?.groups}">
                        %{-- <span id="groups-label" class="property-label"><g:message code="user.groups.label" default="Groups" /></span> --}%
                        <g:link controller='group' action='userGroups' params="${[id: userInstance.id]}" class='btn btn-primary'>
                            <span class="glyphicon glyphicon-th-list"></span>&nbsp;Groups
                        </g:link>
            <hr>
            </g:if>
        </div>
	</body>
</html>