grails-app/domain/org/rankster/Participation.groovy
package org.rankster

class Participation {

    User user
    Rank rank
    Integer votes

    static Membership link(user, rank) {
        def p = Membership.findByUserAndRank(user, rank)
        if (!p)
        {
            p = new Participation(user: user, rank: rank)
            p.save()
        }
        return p
    }

    static void unlink(user, rank) {
        def p = Participation.findByUserAndRank(user, rank)
        if (p)
        {
            user?.removeFromParticipations(p)
            rank?.removeFromParticipations(p)
            p.delete()
        }
    }

    static constraints = {
    }
}

grails-app/controllers/org/rankster/ParticipationController.groovy
package org.rankster



import org.springframework.security.access.annotation.Secured
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
@Secured(['IS_AUTHENTICATED_FULLY'])
class ParticipationController {

    static allowedMethods = [save: "POST", upVote:"GET", update: "PUT", delete: "DELETE"]

    @Transactional
    def upVote(Participation p) {
        p.votes += 1
        p.save flush: true
        redirect controller: "rank", action:"show", id: p.rank.id, method:"GET"
    }
    @Transactional
    def downVote(Participation p) {
        p.votes -= 1
        p.save flush: true
        redirect controller: "rank", action:"show", id: p.rank.id, method:"GET"
    }

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Participation.list(params), model:[participationInstanceCount: Participation.count()]
    }

    def show(Participation participationInstance) {
        respond participationInstance
    }

    def create() {
        respond new Participation(params)
    }

    @Transactional
    def save(Participation participationInstance) {
        if (participationInstance == null) {
            notFound()
            return
        }

        if (participationInstance.hasErrors()) {
            respond participationInstance.errors, view:'create'
            return
        }

        participationInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'participation.label', default: 'Participation'), participationInstance.id])
                redirect participationInstance
            }
            '*' { respond participationInstance, [status: CREATED] }
        }
    }

    def edit(Participation participationInstance) {
        respond participationInstance
    }

    @Transactional
    def update(Participation participationInstance) {
        if (participationInstance == null) {
            notFound()
            return
        }

        if (participationInstance.hasErrors()) {
            respond participationInstance.errors, view:'edit'
            return
        }

        participationInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Participation.label', default: 'Participation'), participationInstance.id])
                redirect participationInstance
            }
            '*'{ respond participationInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Participation participationInstance) {

        if (participationInstance == null) {
            notFound()
            return
        }

        participationInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Participation.label', default: 'Participation'), participationInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'participation.label', default: 'Participation'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/participation/_form.gsp
<%@ page import="org.rankster.Participation" %>



<div class="fieldcontain ${hasErrors(bean: participationInstance, field: 'rank', 'error')} required">
	<label for="rank">
		<g:message code="participation.rank.label" default="Rank" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="rank" name="rank.id" from="${org.rankster.Rank.list()}" optionKey="id" required="" value="${participationInstance?.rank?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: participationInstance, field: 'user', 'error')} required">
	<label for="user">
		<g:message code="participation.user.label" default="User" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="user" name="user.id" from="${org.rankster.User.list()}" optionKey="id" required="" value="${participationInstance?.user?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: participationInstance, field: 'votes', 'error')} required">
	<label for="votes">
		<g:message code="participation.votes.label" default="Votes" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="votes" type="number" value="${participationInstance.votes}" required=""/>

</div>

grails-app/views/participation/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'participation.label', default: 'Participation')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-participation" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-participation" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${participationInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${participationInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:participationInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/participation/edit.gsp
<%@ page import="org.rankster.Participation" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'participation.label', default: 'Participation')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-participation" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-participation" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${participationInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${participationInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:participationInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${participationInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/participation/index.gsp
<%@ page import="org.rankster.Participation" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'participation.label', default: 'Participation')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-participation" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-participation" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="participation.rank.label" default="Rank" /></th>
					
						<th><g:message code="participation.user.label" default="User" /></th>
					
						<g:sortableColumn property="votes" title="${message(code: 'participation.votes.label', default: 'Votes')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${participationInstanceList}" status="i" var="participationInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${participationInstance.id}">${fieldValue(bean: participationInstance, field: "rank")}</g:link></td>
					
						<td>${fieldValue(bean: participationInstance, field: "user")}</td>
					
						<td>${fieldValue(bean: participationInstance, field: "votes")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${participationInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/participation/show.gsp
<%@ page import="org.rankster.Participation" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'participation.label', default: 'Participation')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-participation" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-participation" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list participation">
			
				<g:if test="${participationInstance?.rank}">
				<li class="fieldcontain">
					<span id="rank-label" class="property-label"><g:message code="participation.rank.label" default="Rank" /></span>
					
						<span class="property-value" aria-labelledby="rank-label"><g:link controller="rank" action="show" id="${participationInstance?.rank?.id}">${participationInstance?.rank?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${participationInstance?.user}">
				<li class="fieldcontain">
					<span id="user-label" class="property-label"><g:message code="participation.user.label" default="User" /></span>
					
						<span class="property-value" aria-labelledby="user-label"><g:link controller="user" action="show" id="${participationInstance?.user?.id}">${participationInstance?.user?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${participationInstance?.votes}">
				<li class="fieldcontain">
					<span id="votes-label" class="property-label"><g:message code="participation.votes.label" default="Votes" /></span>
					
						<span class="property-value" aria-labelledby="votes-label"><g:fieldValue bean="${participationInstance}" field="votes"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:participationInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${participationInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>