grails-app/domain/org/rankster/Rank.groovy
package org.rankster

class Rank {

    String title
    String reward
    User publisher
    Group parent
    Date startDate
    Date endDate

    static belongsTo = [User, Group]
    static hasMany = [participations: Participation]

    static constraints = {
    }
	String toString(){
		return title
	}
}

grails-app/controllers/org/rankster/RankController.groovy
package org.rankster


import org.springframework.security.access.annotation.Secured
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
@Secured(['IS_AUTHENTICATED_FULLY'])
class RankController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Rank.list(params), model:[rankInstanceCount: Rank.count()]
    }

    def show(Rank rankInstance) {
        respond rankInstance
    }

    def create() {
        respond new Rank(params)
    }

    @Transactional
    def save(Rank rankInstance) {
        if (rankInstance == null) {
            notFound()
            return
        }

        if (rankInstance.hasErrors()) {
            respond rankInstance.errors, view:'create'
            return
        }

        rankInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'rank.label', default: 'Rank'), rankInstance.id])
                redirect rankInstance
            }
            '*' { respond rankInstance, [status: CREATED] }
        }
    }

    def edit(Rank rankInstance) {
        respond rankInstance
    }

    @Transactional
    def update(Rank rankInstance) {
        if (rankInstance == null) {
            notFound()
            return
        }

        if (rankInstance.hasErrors()) {
            respond rankInstance.errors, view:'edit'
            return
        }

        rankInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Rank.label', default: 'Rank'), rankInstance.id])
                redirect rankInstance
            }
            '*'{ respond rankInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Rank rankInstance) {

        if (rankInstance == null) {
            notFound()
            return
        }

        rankInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Rank.label', default: 'Rank'), rankInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'rank.label', default: 'Rank'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/rank/_form.gsp
<%@ page import="org.rankster.Rank" %>



<div class="fieldcontain ${hasErrors(bean: rankInstance, field: 'endDate', 'error')} required">
	<label for="endDate">
		<g:message code="rank.endDate.label" default="End Date" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="endDate" precision="day"  value="${rankInstance?.endDate}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: rankInstance, field: 'parent', 'error')} required">
	<label for="parent">
		<g:message code="rank.parent.label" default="Parent" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="parent" name="parent.id" from="${org.rankster.Group.list()}" optionKey="id" required="" value="${rankInstance?.parent?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: rankInstance, field: 'participations', 'error')} ">
	<label for="participations">
		<g:message code="rank.participations.label" default="Participations" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${rankInstance?.participations?}" var="p">
    <li><g:link controller="participation" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="participation" action="create" params="['rank.id': rankInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'participation.label', default: 'Participation')])}</g:link>
</li>
</ul>


</div>

<div class="fieldcontain ${hasErrors(bean: rankInstance, field: 'publisher', 'error')} required">
	<label for="publisher">
		<g:message code="rank.publisher.label" default="Publisher" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="publisher" name="publisher.id" from="${org.rankster.User.list()}" optionKey="id" required="" value="${rankInstance?.publisher?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: rankInstance, field: 'reward', 'error')} required">
	<label for="reward">
		<g:message code="rank.reward.label" default="Reward" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="reward" required="" value="${rankInstance?.reward}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: rankInstance, field: 'startDate', 'error')} required">
	<label for="startDate">
		<g:message code="rank.startDate.label" default="Start Date" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="startDate" precision="day"  value="${rankInstance?.startDate}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: rankInstance, field: 'title', 'error')} required">
	<label for="title">
		<g:message code="rank.title.label" default="Title" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="title" required="" value="${rankInstance?.title}"/>

</div>

grails-app/views/rank/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'rank.label', default: 'Rank')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-rank" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-rank" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${rankInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${rankInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:rankInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/rank/edit.gsp
<%@ page import="org.rankster.Rank" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'rank.label', default: 'Rank')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-rank" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-rank" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${rankInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${rankInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:rankInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${rankInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/rank/index.gsp
<%@ page import="org.rankster.Rank" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'rank.label', default: 'Rank')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-rank" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-rank" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="endDate" title="${message(code: 'rank.endDate.label', default: 'End Date')}" />
					
						<th><g:message code="rank.parent.label" default="Parent" /></th>
					
						<th><g:message code="rank.publisher.label" default="Publisher" /></th>
					
						<g:sortableColumn property="reward" title="${message(code: 'rank.reward.label', default: 'Reward')}" />
					
						<g:sortableColumn property="startDate" title="${message(code: 'rank.startDate.label', default: 'Start Date')}" />
					
						<g:sortableColumn property="title" title="${message(code: 'rank.title.label', default: 'Title')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${rankInstanceList}" status="i" var="rankInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${rankInstance.id}">${fieldValue(bean: rankInstance, field: "endDate")}</g:link></td>
					
						<td>${fieldValue(bean: rankInstance, field: "parent")}</td>
					
						<td>${fieldValue(bean: rankInstance, field: "publisher")}</td>
					
						<td>${fieldValue(bean: rankInstance, field: "reward")}</td>
					
						<td><g:formatDate date="${rankInstance.startDate}" /></td>
					
						<td>${fieldValue(bean: rankInstance, field: "title")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${rankInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/rank/show.gsp
<%@ page import="org.rankster.Rank" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'rank.label', default: 'Rank')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-rank" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-rank" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list rank">

				<g:if test="${rankInstance?.endDate}">
				<li class="fieldcontain">
					<span id="endDate-label" class="property-label"><g:message code="rank.endDate.label" default="End Date" /></span>

						<span class="property-value" aria-labelledby="endDate-label"><g:formatDate date="${rankInstance?.endDate}" /></span>

				</li>
				</g:if>

				<g:if test="${rankInstance?.parent}">
				<li class="fieldcontain">
					<span id="parent-label" class="property-label"><g:message code="rank.parent.label" default="Parent" /></span>

						<span class="property-value" aria-labelledby="parent-label"><g:link controller="group" action="show" id="${rankInstance?.parent?.id}">${rankInstance?.parent?.encodeAsHTML()}</g:link></span>

				</li>
				</g:if>

				<g:if test="${rankInstance?.participations}">
				<li class="fieldcontain">
					<span id="participations-label" class="property-label"><g:message code="rank.participations.label" default="Participations" /></span>

						<g:each in="${rankInstance.participations}" var="p">
						<span class="property-value" aria-labelledby="participations-label"><g:link controller="participation" action="show" id="${p.id}">${p?.encodeAsHTML()}</g:link></span>
						</g:each>

				</li>
				</g:if>

				<g:if test="${rankInstance?.publisher}">
				<li class="fieldcontain">
					<span id="publisher-label" class="property-label"><g:message code="rank.publisher.label" default="Publisher" /></span>

						<span class="property-value" aria-labelledby="publisher-label"><g:link controller="user" action="show" id="${rankInstance?.publisher?.id}">${rankInstance?.publisher?.encodeAsHTML()}</g:link></span>

				</li>
				</g:if>

				<g:if test="${rankInstance?.reward}">
				<li class="fieldcontain">
					<span id="reward-label" class="property-label"><g:message code="rank.reward.label" default="Reward" /></span>

						<span class="property-value" aria-labelledby="reward-label"><g:fieldValue bean="${rankInstance}" field="reward"/></span>

				</li>
				</g:if>

				<g:if test="${rankInstance?.startDate}">
				<li class="fieldcontain">
					<span id="startDate-label" class="property-label"><g:message code="rank.startDate.label" default="Start Date" /></span>

						<span class="property-value" aria-labelledby="startDate-label"><g:formatDate date="${rankInstance?.startDate}" /></span>

				</li>
				</g:if>

				<g:if test="${rankInstance?.title}">
				<li class="fieldcontain">
					<span id="title-label" class="property-label"><g:message code="rank.title.label" default="Title" /></span>

						<span class="property-value" aria-labelledby="title-label"><g:fieldValue bean="${rankInstance}" field="title"/></span>

				</li>
				</g:if>

				<div class="row">
					<div class="col-md-4">
						Participations	:
				<g:if test="${rankInstance?.participations}">
						<ul class="list-group" >
						<g:each in="${rankInstance.participations}" status="i" var="p">
							<li class="list-group-item" > User: <g:link controller="participation" action="show" id="${p.id}">${p?.user?.encodeAsHTML()}</g:link> Votes:  ${p.votes}</li>
							<g:link action="upVote" resource="${p}"><g:message code="default.button.upvote.label" default="UpVote" /></g:link>
							<g:link action="downVote" resource="${p}"><g:message code="default.button.downvote.label" default="DownVote" /></g:link>
						</g:each>
						</ul>
				</g:if>
					</div>
					<div class="col-md-4">
					</div>
				</div>

			</ol>
			<g:form url="[resource:rankInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${rankInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>