grails-app/domain/org/rankster/Membership.groovy
package org.rankster

class Membership {

    User user
    Group group

    static Membership link(user, group) {
        def m = Membership.findByUserAndGroup(user, group)
        if (!m)
        {
            m = new Membership(user: user, group: group)
            m.save()
        }
        return m
    }

    static void unlink(user, group) {
        def m = Membership.findByUserAndGroup(user, group)
        if (m)
        {

            user?.removeFromMemberships(m)
            group?.removeFromMemberships(m)
            m.delete()
        }
    }

    static constraints = {
    }
	String toString(){
		return "Group = "+group+"User = "+user
	}
}

grails-app/controllers/org/rankster/MembershipController.groovy
package org.rankster


import org.springframework.security.access.annotation.Secured
import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
@Secured(['IS_AUTHENTICATED_FULLY'])
class MembershipController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Membership.list(params), model:[membershipInstanceCount: Membership.count()]
    }

    def show(Membership membershipInstance) {
        respond membershipInstance
    }

    def create() {
        respond new Membership(params)
    }

    @Transactional
    def save(Membership membershipInstance) {
        if (membershipInstance == null) {
            notFound()
            return
        }

        if (membershipInstance.hasErrors()) {
            respond membershipInstance.errors, view:'create'
            return
        }

        membershipInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'membership.label', default: 'Membership'), membershipInstance.id])
                redirect membershipInstance
            }
            '*' { respond membershipInstance, [status: CREATED] }
        }
    }

    def edit(Membership membershipInstance) {
        respond membershipInstance
    }

    @Transactional
    def update(Membership membershipInstance) {
        if (membershipInstance == null) {
            notFound()
            return
        }

        if (membershipInstance.hasErrors()) {
            respond membershipInstance.errors, view:'edit'
            return
        }

        membershipInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Membership.label', default: 'Membership'), membershipInstance.id])
                redirect membershipInstance
            }
            '*'{ respond membershipInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Membership membershipInstance) {

        if (membershipInstance == null) {
            notFound()
            return
        }

        membershipInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Membership.label', default: 'Membership'), membershipInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'membership.label', default: 'Membership'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/membership/_form.gsp
<%@ page import="org.rankster.Membership" %>



<div class="fieldcontain ${hasErrors(bean: membershipInstance, field: 'group', 'error')} required">
	<label for="group">
		<g:message code="membership.group.label" default="Group" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="group" name="group.id" from="${org.rankster.Group.list()}" optionKey="id" required="" value="${membershipInstance?.group?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: membershipInstance, field: 'user', 'error')} required">
	<label for="user">
		<g:message code="membership.user.label" default="User" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="user" name="user.id" from="${org.rankster.User.list()}" optionKey="id" required="" value="${membershipInstance?.user?.id}" class="many-to-one"/>

</div>

grails-app/views/membership/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'membership.label', default: 'Membership')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-membership" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-membership" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${membershipInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${membershipInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:membershipInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/membership/edit.gsp
<%@ page import="org.rankster.Membership" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'membership.label', default: 'Membership')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-membership" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-membership" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${membershipInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${membershipInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:membershipInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${membershipInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/membership/index.gsp
<%@ page import="org.rankster.Membership" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'membership.label', default: 'Membership')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-membership" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-membership" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="membership.group.label" default="Group" /></th>
					
						<th><g:message code="membership.user.label" default="User" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${membershipInstanceList}" status="i" var="membershipInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${membershipInstance.id}">${fieldValue(bean: membershipInstance, field: "group")}</g:link></td>
					
						<td>${fieldValue(bean: membershipInstance, field: "user")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${membershipInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/membership/show.gsp
<%@ page import="org.rankster.Membership" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'membership.label', default: 'Membership')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-membership" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-membership" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list membership">
			
				<g:if test="${membershipInstance?.group}">
				<li class="fieldcontain">
					<span id="group-label" class="property-label"><g:message code="membership.group.label" default="Group" /></span>
					
						<span class="property-value" aria-labelledby="group-label"><g:link controller="group" action="show" id="${membershipInstance?.group?.id}">${membershipInstance?.group?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${membershipInstance?.user}">
				<li class="fieldcontain">
					<span id="user-label" class="property-label"><g:message code="membership.user.label" default="User" /></span>
					
						<span class="property-value" aria-labelledby="user-label"><g:link controller="user" action="show" id="${membershipInstance?.user?.id}">${membershipInstance?.user?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:membershipInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${membershipInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>